LastBox/Models/SurveyModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace LastBox.Models
{
    public class SurveyModel
    {
        public int ID { get; set; }
        public int Gender { get; set; }
        public int Age { get; set; }
        public int maxMoney { get; set; }
        public bool Alcohol { get; set; }
        public bool Presentable { get; set; }
        public bool Books { get; set; }
        public bool Candles { get; set; }
        public bool Candy { get; set; }
        public bool Clothes { get; set; }
        public bool Coffee { get; set; }
        public bool Fitness { get; set; }
        public bool Games { get; set; }
        public bool Movies { get; set; }
        public bool Music { get; set; }
        public bool Sports { get; set; }
        public int Active { get; set; }
        public int Candle { get; set; }
        public int Entertainment { get; set; }
        public int FoodORdrink { get; set; }
        public int Appearance { get; set; }
        public static Box Box { get; set; }


    }
}

LastBox/Controllers/SubscribeController.cs
using LastBox.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LastBox.Controllers
{
    public class SubscribeController : Controller
    {
        // GET: Subscribe
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SubmitForm(Subscribe subscribe)
        {
            bool purchased = subscribe.Purchase;
            if (purchased == true)
            {

                TempData["BoxName"] = Session["SubBox"];
                TempData["BoxPrice"] = Session["SubPrice"];
                return RedirectToAction("../Manage/Index");
            }
            else
            {
                return View("Index");
            }

        }
    }
}

LastBox/Controllers/SurveyModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LastBox.Models;

namespace LastBox.Controllers
{
    public class SurveyModelsController : Controller
    {
        private RegisteredUserDbContext db = new RegisteredUserDbContext();
        BoxesController bc;
        public ActionResult ViewBoxRecommendation(Box box)
        {
            return View();
            //db.SurveyResponses.Select(x => x).Where(x => x.Age < 21);

        }

        [HttpGet]
        public ActionResult GoToSurvey()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GoToSurvey([Bind(Include = "ID,gender,age,Money,alcohol,presentable, books, candles, candy, clothes, coffee, fitness, games, movies, music, sports, active, candle, entertainment, foodORdrink, appearance")] SurveyModel surveyModel)
        {
            if (ModelState.IsValid)
            {

                db.SurveyResponses.Add(surveyModel);
                db.SaveChanges();
                return RedirectToAction("Index", surveyModel);
            }

            return View("Index", surveyModel);
        }

        // GET: SurveyModels
        public ActionResult Index()
        {
            return View(db.SurveyResponses.ToList());
        }

        // GET: SurveyModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SurveyModel surveyModel = db.SurveyResponses.Find(id);
            if (surveyModel == null)
            {
                return HttpNotFound();
            }
            return View(surveyModel);
        }

        // GET: SurveyModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SurveyModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,gender,age,Money,alcohol,presentable,books,candles,candy,clothes,coffee,fitness,games,movies,music,sports,active,candle,entertainment,foodORdrink,looks")] SurveyModel surveyModel)
        {
            if (ModelState.IsValid)
            {
                db.SurveyResponses.Add(surveyModel);
                db.SaveChanges();

                return RedirectToAction("GetCurrentSurveyResults", surveyModel);  //change "Index" to "GetCurrentSurveyResults" and add ,surveyModel
            }

            return View(surveyModel);
        }

        // GET: SurveyModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SurveyModel surveyModel = db.SurveyResponses.Find(id);
            if (surveyModel == null)
            {
                return HttpNotFound();
            }
            return View(surveyModel);
        }

        // POST: SurveyModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,gender,age,Money,alcohol,presentable,books,candles,candy,clothes,coffee,fitness,games,movies,music,sports,active,candle,entertainment,foodORdrink,looks")] SurveyModel surveyModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(surveyModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("GetSurveyResults"); //change from index to results page
            }
            return View(surveyModel);
        }

        // GET: SurveyModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SurveyModel surveyModel = db.SurveyResponses.Find(id);
            if (surveyModel == null)
            {
                return HttpNotFound();
            }
            return View(surveyModel);
        }

        // POST: SurveyModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SurveyModel surveyModel = db.SurveyResponses.Find(id);
            db.SurveyResponses.Remove(surveyModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult GetCurrentSurveyResults(SurveyModel sm)
        {
            int age = sm.Age;
            int money = sm.maxMoney;
            int active = sm.Active;
            int candle = sm.Candle;
            int entertainment = sm.Entertainment;
            int foodORdrink = sm.FoodORdrink;
            int looks = sm.Appearance;
            int gender = sm.Gender;
            bool alcohol = sm.Alcohol;
            bool presentable = sm.Presentable;
            bool books = sm.Books;
            bool candles = sm.Candles;
            bool candy = sm.Candy;
            bool clothes = sm.Clothes;
            bool coffee = sm.Coffee;
            bool fitness = sm.Fitness;
            bool games = sm.Games;
            bool movies = sm.Movies;
            bool music = sm.Music;
            bool sports = sm.Sports;
            Box box = new Box();
            Box ofBeer = new Box();
            BoxContents Highlife = new BoxContents("Highlife");
            BoxContents PBR = new BoxContents("PBR");
            BoxContents Corona = new BoxContents("Corona");
            Box ofWine = new Box();
            BoxContents Moscato = new BoxContents("Moscato");
            BoxContents Chardonnay = new BoxContents("Chardonnay");
            Box ofCandles = new Box();
            BoxContents Aromatherapy = new BoxContents("Aromatherapy Candle");
            BoxContents Fruit = new BoxContents("Fruit-scented Candle");
            BoxContents Flower = new BoxContents("Flower=scented Candle");
            Box ofFitness = new Box();
            BoxContents Shake = new BoxContents("Shake Weight");
            Box ofGames = new Box();
            BoxContents Scrabble = new BoxContents("Scrabble");
            BoxContents Yahtzee = new BoxContents("Yahtzee");
            Box ofMovies = new Box();
            BoxContents DieHard = new BoxContents("Die Hard");
            BoxContents BigGreen = new BoxContents("The Big Green");
            BoxContents PT = new BoxContents("Pootie Tang");
            Box ofMusic = new Box();
            BoxContents CW = new BoxContents("Chumbawamba- Tubthumper");
            Box ofCandy = new Box();
            BoxContents Nerds = new BoxContents("Nerds");
            BoxContents MM = new BoxContents("M&Ms");
            BoxContents Skittles = new BoxContents("Skittles");
            Box ofCoffee = new Box();
            BoxContents Beans = new BoxContents("Generic Coffee Beans");
            Box ofAppearanceM = new Box();
            BoxContents Razor = new BoxContents("Shaving kit");
            Box ofAppearanceF = new Box();
            BoxContents Lipstick = new BoxContents("Lipstick");
            BoxContents Mascara = new BoxContents("Mascara");



            if (age > 1 && alcohol == true && gender == 1 && money == 3)
            {

                ofBeer.Name = "Beer Box";
                ofBeer.Category = "Alcohol";
                ofBeer.Description = "This box contains various beers in it.";
                ofBeer.Cost = 30;
                ofBeer.Contents = new List<BoxContents>();

                ofBeer.Contents.Add(Highlife);
                ofBeer.Contents.Add(PBR);
                ofBeer.Contents.Add(Corona);

                box = ofBeer;

            }
            else if (age > 1 && alcohol == true && gender == 2 && money == 3)
            {
                ofWine.Name = "Wine Box";
                ofWine.Category = "Alcohol";
                ofWine.Description = "This box contains two bottles of wine";
                ofWine.Cost = 30;

                ofWine.Contents = new List<BoxContents>();
                ofWine.Contents.Add(Moscato);
                ofWine.Contents.Add(Chardonnay);

                box = ofWine;

            }
            else if (candle > 1 && candles == true)
            {
                ofCandles.Name = "Candle Box";
                ofCandles.Category = "Candles";
                ofCandles.Description = "This box contains three candles.";
                ofCandles.Cost = 15;
                ofCandles.Contents = new List<BoxContents>();
                ofCandles.Contents.Add(Aromatherapy);
                ofCandles.Contents.Add(Flower);
                ofCandles.Contents.Add(Fruit);
                box = ofCandles;

            }
            else if (active > 1 && fitness == true && money > 1)
            {

                ofFitness.Name = "Fitness Box";
                ofFitness.Category = "Fitness";
                ofFitness.Description = "This box contains a fitness item.";
                ofFitness.Cost = 20;
                ofFitness.Contents = new List<BoxContents>();

                ofFitness.Contents.Add(Shake);
                box = ofFitness;

            }
            else if (entertainment > 1 && games == true)
            {
                ofGames.Name = "Game Box";

LastBox/Views/SurveyModels/Create.cshtml
@model LastBox.Models.SurveyModel

@{
    ViewBag.Title = "Create";
}

<h2>Box Recommendation Survey</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div><h4>Select your gender</h4></div>
    <div class="form-group">
        <div class="col-md-10" style="color:black">
            @{var listItems = new List<SelectListItem>
                ()
                {
                new SelectListItem {Text = "Male",   Value = "1"},
                new SelectListItem {Text = "Female", Value = "2"},
                };

                @Html.DropDownListFor(model => model.Gender, listItems)
                }
        </div>
    </div>
    @*<div class="form-group">
        @Html.LabelFor(model => model.Male, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Male)
                @Html.ValidationMessageFor(model => model.Male, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Female, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Female)
                @Html.ValidationMessageFor(model => model.Female, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>*@
    <div><h4>How old are you?</h4></div>
    <div class="form-group">
        <div class="col-md-10" style="color:black">
            @{var listItems7 = new List<SelectListItem>
                ()
                {
                new SelectListItem {Text = "14-20",   Value = "1"},
                new SelectListItem {Text = "21-30", Value = "2"},
                new SelectListItem {Text = "Over 30", Value = "3" },
                };

                @Html.DropDownListFor(model => model.Age, listItems7)
                }
        </div>
    </div>
    <div><h4>What is the most you are willing to spend on a box subscription this month?</h4></div>
    <div class="form-group">
        <div class="col-md-10" style="color:black">
            @{var listItems8 = new List<SelectListItem>
                ()
                {
                new SelectListItem {Text = "$15",   Value = "1"},
                new SelectListItem {Text = "$25", Value = "2"},
                new SelectListItem {Text = "$50", Value = "3" }
                };

                @Html.DropDownListFor(model => model.maxMoney, listItems8)
                }
        </div>
    </div>
    @*<div class="form-group">
        @Html.LabelFor(model => model.Money, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Money, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Money, "", new { @class = "text-danger" })
        </div>
    </div>*@
    <div><h4>Select some of your interests...</h4></div>
    <div class="form-group">
        @Html.LabelFor(model => model.Alcohol, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Alcohol)
                @Html.ValidationMessageFor(model => model.Alcohol, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Presentable, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Presentable)
                @Html.ValidationMessageFor(model => model.Presentable, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Books, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Books)
                @Html.ValidationMessageFor(model => model.Books, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Candles, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Candles)
                @Html.ValidationMessageFor(model => model.Candles, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Candy, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Candy)
                @Html.ValidationMessageFor(model => model.Candy, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Clothes, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Clothes)
                @Html.ValidationMessageFor(model => model.Clothes, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Coffee, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Coffee)
                @Html.ValidationMessageFor(model => model.Coffee, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Fitness, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Fitness)
                @Html.ValidationMessageFor(model => model.Fitness, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Games, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Games)
                @Html.ValidationMessageFor(model => model.Games, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Movies, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Movies)
                @Html.ValidationMessageFor(model => model.Movies, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Music, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Music)
                @Html.ValidationMessageFor(model => model.Music, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sports, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Sports)
                @Html.ValidationMessageFor(model => model.Sports, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div><h4>How interested are you in...</h4></div>
    <div><h5>Being active</h5></div>
    @*<div class="form-group">
        @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Active, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
        </div>
    </div>*@
    <div class="form-group">
        <div class="col-md-10" style="color:black">
            @{var listItems2 = new List<SelectListItem>
                ()
                {
                new SelectListItem {Text = "Not Interested",   Value = "1"},
                new SelectListItem {Text = "Somewhat Interested", Value = "2"},
                new SelectListItem {Text = "Very Interested", Value= "3" },
                };

                @Html.DropDownListFor(model => model.Active, listItems2)
                }
        </div>
    </div>
    <div><h5>Things that smell good</h5></div>
    <div class="form-group">
        <div class="col-md-10" style="color:black">
            @{var listItems3 = new List<SelectListItem>
                ()
                {
                new SelectListItem {Text = "Not Interested",   Value = "1"},
                new SelectListItem {Text = "Somewhat Interested", Value = "2"},
                new SelectListItem {Text = "Very Interested", Value= "3" },
                };

                @Html.DropDownListFor(model => model.Candle, listItems2)
                }
        </div>
    </div>
    <div><h5>Entertainment</h5></div>
    <div class="form-group">
        <div class="col-md-10" style="color:black">
            @{var listItems4 = new List<SelectListItem>
                ()
                {
                new SelectListItem {Text = "Not Interested",   Value = "1"},
                new SelectListItem {Text = "Somewhat Interested", Value = "2"},
                new SelectListItem {Text = "Very Interested", Value= "3" },
                };

                @Html.DropDownListFor(model => model.Entertainment, listItems2)
                }
        </div>
    </div>
    <div><h5>Food/Drink</h5></div>
    <div class="form-group">
        <div class="col-md-10" style="color:black">
            @{var listItems5 = new List<SelectListItem>
                ()
                {
                new SelectListItem {Text = "Not Interested",   Value = "1"},
                new SelectListItem {Text = "Somewhat Interested", Value = "2"},
                new SelectListItem {Text = "Very Interested", Value= "3" },
                };

                @Html.DropDownListFor(model => model.FoodORdrink, listItems2)
                }
        </div>
    </div>
    <div><h5>Your appearance</h5></div>
    <div class="form-group">
        <div class="col-md-10" style="color:black">
            @{var listItems6 = new List<SelectListItem>
                ()
                {
                new SelectListItem {Text = "Not Interested",   Value = "1"},
                new SelectListItem {Text = "Somewhat Interested", Value = "2"},
                new SelectListItem {Text = "Very Interested", Value= "3" },
                };

                @Html.DropDownListFor(model => model.Appearance, listItems2)
                }
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.Candle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Candle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Candle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Entertainment, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Entertainment, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Entertainment, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.foodORdrink, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.foodORdrink, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.foodORdrink, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Looks, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Looks, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Looks, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Submit" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LastBox/Views/SurveyModels/Delete.cshtml
@model LastBox.Models.SurveyModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SurveyModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Money)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Money)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alcohol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alcohol)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Appearance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Appearance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Books)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Books)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Candles)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Candles)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Candy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Candy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Clothes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Clothes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Coffee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coffee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fitness)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fitness)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Games)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Games)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Movies)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Movies)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Music)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Music)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sports)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sports)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Candle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Candle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Entertainment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Entertainment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.foodORdrink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.foodORdrink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Looks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Looks)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LastBox/Views/SurveyModels/GetCurrentSurveyResults.cshtml
@model LastBox.Models.Subscribe
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = "GetCurrentSurveyResults";
}
<h1>
    Survey Results
</h1>
@using (Html.BeginForm("SubmitForm", "Subscribe", FormMethod.Post, new { id = "submitForm" }))
{
    <table class="table">
        <tr>
            <th>
                Name
            </th>
            <th>
                Category
            </th>
            <th>
                Description
            </th>
            <th>
                Cost ($)
            </th>
            <th>
                Subscribe
            </th>
            <th></th>
        </tr>

        <tr>
            <td>
                @ViewBag.BoxName
            </td>
            <td>
                @ViewBag.BoxCategory
            </td>
            <td>
                @ViewBag.BoxDescription
            </td>
            <td>
                @ViewBag.BoxCost
            </td>
            <td>
                <div class="form-group">
                    @Html.LabelFor(model => model.Purchase, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Purchase)
                            @Html.ValidationMessageFor(model => model.Purchase, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Purchase" class="btn btn-default" />
                    </div>
                </div>
            </td>
        </tr>
        }

    </table>
}